//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgenciaDeViajes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aeropuerto
    {
        public Aeropuerto()
        {
            this.ProgVuelo = new HashSet<ProgVuelo>();
            this.ProgVuelo1 = new HashSet<ProgVuelo>();
            this.ProgVuelo2 = new HashSet<ProgVuelo>();
        }
    
        public string idAeropuerto { get; set; }
        public string nombAeropuerto { get; set; }
        public string idPais { get; set; }
        public string idCiudad { get; set; }
        public string direcAeropuerto { get; set; }
    
        public virtual Ciudad Ciudad { get; set; }
        public virtual Pais Pais { get; set; }
        public virtual ICollection<ProgVuelo> ProgVuelo { get; set; }
        public virtual ICollection<ProgVuelo> ProgVuelo1 { get; set; }
        public virtual ICollection<ProgVuelo> ProgVuelo2 { get; set; }
    }
}
