//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgenciaDeViajes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Avion
    {
        public Avion()
        {
            this.ProgVuelo = new HashSet<ProgVuelo>();
        }
    
        public string idAvion { get; set; }
        public string idProveedor { get; set; }
        public string modelAvion { get; set; }
    
        public virtual Proveedor Proveedor { get; set; }
        public virtual ICollection<ProgVuelo> ProgVuelo { get; set; }
    }
}
