//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgenciaDeViajes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ciudad
    {
        public Ciudad()
        {
            this.Aeropuertoes = new HashSet<Aeropuerto>();
            this.Clientes = new HashSet<Cliente>();
            this.Empleadoes = new HashSet<Empleado>();
            this.GestionPaquetes = new HashSet<GestionPaquete>();
            this.Proveedors = new HashSet<Proveedor>();
        }
    
        public string idCiudad { get; set; }
        public string idPais { get; set; }
        public string nombCiudad { get; set; }
    
        public virtual ICollection<Aeropuerto> Aeropuertoes { get; set; }
        public virtual Pai Pai { get; set; }
        public virtual ICollection<Cliente> Clientes { get; set; }
        public virtual ICollection<Empleado> Empleadoes { get; set; }
        public virtual ICollection<GestionPaquete> GestionPaquetes { get; set; }
        public virtual ICollection<Proveedor> Proveedors { get; set; }
    }
}
