//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgenciaDeViajes.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EasyTravelEntities1 : DbContext
    {
        public EasyTravelEntities1()
            : base("name=EasyTravelEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Aeropuerto> Aeropuerto { get; set; }
        public DbSet<Avion> Avion { get; set; }
        public DbSet<Cargo> Cargo { get; set; }
        public DbSet<CategoriaHotel> CategoriaHotel { get; set; }
        public DbSet<Ciudad> Ciudad { get; set; }
        public DbSet<Cliente> Cliente { get; set; }
        public DbSet<Empleado> Empleado { get; set; }
        public DbSet<EstadoReserva> EstadoReserva { get; set; }
        public DbSet<GestionPaquete> GestionPaquete { get; set; }
        public DbSet<Habitacion> Habitacion { get; set; }
        public DbSet<Pais> Pais { get; set; }
        public DbSet<ProgVuelo> ProgVuelo { get; set; }
        public DbSet<Proveedor> Proveedor { get; set; }
        public DbSet<Reserva> Reserva { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<TipoHabitacion> TipoHabitacion { get; set; }
        public DbSet<TipoPaquete> TipoPaquete { get; set; }
        public DbSet<TipoServicio> TipoServicio { get; set; }
    }
}
