//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgenciaDeViajes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GestionPaquete
    {
        public GestionPaquete()
        {
            this.Reserva = new HashSet<Reserva>();
        }
    
        public string idPaquete { get; set; }
        public string idTipopaquete { get; set; }
        public string nombPaquete { get; set; }
        public string idPais { get; set; }
        public string idCiudad { get; set; }
        public System.DateTime iniciodisponibilidad { get; set; }
        public System.DateTime findisponibilidad { get; set; }
        public string idProgVuelo { get; set; }
        public string servIncluidos { get; set; }
        public string servAdicional { get; set; }
        public string infoPaquete { get; set; }
        public decimal precioPaqueteAdulto { get; set; }
        public decimal precioPaqueteNiño { get; set; }
    
        public virtual Ciudad Ciudad { get; set; }
        public virtual Pais Pais { get; set; }
        public virtual ProgVuelo ProgVuelo { get; set; }
        public virtual TipoPaquete TipoPaquete { get; set; }
        public virtual ICollection<Reserva> Reserva { get; set; }
    }
}
