//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgenciaDeViajes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Habitacion
    {
        public string idHabitacion { get; set; }
        public string idProveedor { get; set; }
        public string idCategoriaHotel { get; set; }
        public string estado { get; set; }
        public string idTipoHabitacion { get; set; }
        public Nullable<int> numCamas { get; set; }
    
        public virtual CategoriaHotel CategoriaHotel { get; set; }
        public virtual Proveedor Proveedor { get; set; }
        public virtual TipoHabitacion TipoHabitacion { get; set; }
    }
}
