//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgenciaDeViajes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pai
    {
        public Pai()
        {
            this.Aeropuertoes = new HashSet<Aeropuerto>();
            this.Ciudads = new HashSet<Ciudad>();
            this.Clientes = new HashSet<Cliente>();
            this.Empleadoes = new HashSet<Empleado>();
            this.GestionPaquetes = new HashSet<GestionPaquete>();
            this.Proveedors = new HashSet<Proveedor>();
        }
    
        public string idPais { get; set; }
        public string nombPais { get; set; }
    
        public virtual ICollection<Aeropuerto> Aeropuertoes { get; set; }
        public virtual ICollection<Ciudad> Ciudads { get; set; }
        public virtual ICollection<Cliente> Clientes { get; set; }
        public virtual ICollection<Empleado> Empleadoes { get; set; }
        public virtual ICollection<GestionPaquete> GestionPaquetes { get; set; }
        public virtual ICollection<Proveedor> Proveedors { get; set; }
    }
}
