//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgenciaDeViajes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pais
    {
        public Pais()
        {
            this.Aeropuerto = new HashSet<Aeropuerto>();
            this.Ciudad = new HashSet<Ciudad>();
            this.Cliente = new HashSet<Cliente>();
            this.Empleado = new HashSet<Empleado>();
            this.GestionPaquete = new HashSet<GestionPaquete>();
            this.Proveedor = new HashSet<Proveedor>();
        }
    
        public string idPais { get; set; }
        public string nombPais { get; set; }
    
        public virtual ICollection<Aeropuerto> Aeropuerto { get; set; }
        public virtual ICollection<Ciudad> Ciudad { get; set; }
        public virtual ICollection<Cliente> Cliente { get; set; }
        public virtual ICollection<Empleado> Empleado { get; set; }
        public virtual ICollection<GestionPaquete> GestionPaquete { get; set; }
        public virtual ICollection<Proveedor> Proveedor { get; set; }
    }
}
