//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgenciaDeViajes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proveedor
    {
        public Proveedor()
        {
            this.Avion = new HashSet<Avion>();
            this.Habitacion = new HashSet<Habitacion>();
            this.ProgVuelo = new HashSet<ProgVuelo>();
        }
    
        public string idProveedor { get; set; }
        public string idTipoServicio { get; set; }
        public string nombProveedor { get; set; }
        public string rucProveedor { get; set; }
        public string idPais { get; set; }
        public string idCiudad { get; set; }
        public string direcProveedor { get; set; }
    
        public virtual ICollection<Avion> Avion { get; set; }
        public virtual Ciudad Ciudad { get; set; }
        public virtual ICollection<Habitacion> Habitacion { get; set; }
        public virtual Pais Pais { get; set; }
        public virtual ICollection<ProgVuelo> ProgVuelo { get; set; }
        public virtual TipoServicio TipoServicio { get; set; }
    }
}
