//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgenciaDeViajes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proveedor
    {
        public Proveedor()
        {
            this.Avions = new HashSet<Avion>();
            this.Habitacions = new HashSet<Habitacion>();
            this.ProgVueloes = new HashSet<ProgVuelo>();
        }
    
        public string idProveedor { get; set; }
        public string idTipoServicio { get; set; }
        public string nombProveedor { get; set; }
        public string rucProveedor { get; set; }
        public string idPais { get; set; }
        public string idCiudad { get; set; }
        public string direcProveedor { get; set; }
    
        public virtual ICollection<Avion> Avions { get; set; }
        public virtual Ciudad Ciudad { get; set; }
        public virtual ICollection<Habitacion> Habitacions { get; set; }
        public virtual Pai Pai { get; set; }
        public virtual ICollection<ProgVuelo> ProgVueloes { get; set; }
        public virtual TipoServicio TipoServicio { get; set; }
    }
}
