//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgenciaDeViajes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reserva
    {
        public string nroReserva { get; set; }
        public string idPaquete { get; set; }
        public string nombreContacto { get; set; }
        public string apellidopatContacto { get; set; }
        public string apellidomatContacto { get; set; }
        public string direccionContacto { get; set; }
        public string correoContacto { get; set; }
        public string idEstadoReserva { get; set; }
        public Nullable<System.DateTime> fechareserva { get; set; }
        public string nroPago { get; set; }
    
        public virtual GestionPaquete GestionPaquete { get; set; }
    }
}
