//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgenciaDeViajes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoPaquete
    {
        public TipoPaquete()
        {
            this.GestionPaquetes = new HashSet<GestionPaquete>();
        }
    
        public string idTipoPaquete { get; set; }
        public string nombTipoPaquete { get; set; }
    
        public virtual ICollection<GestionPaquete> GestionPaquetes { get; set; }
    }
}
