//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgenciaDeViajes.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoServicio
    {
        public TipoServicio()
        {
            this.Proveedor = new HashSet<Proveedor>();
        }
    
        public string idTipoServicio { get; set; }
        public string Servicio { get; set; }
    
        public virtual ICollection<Proveedor> Proveedor { get; set; }
    }
}
